spring.application.name=pgt

spring.datasource.url=jdbc:postgresql://localhost:5432/pgt
spring.datasource.username=postgres
spring.datasource.password=postgres

# Hibernate se encarga de crear tablas a partir de los Entities
spring.jpa.hibernate.ddl-auto=update

# Por defecto el maximo es 1MB, con esto ajustamos a lo que necesita la plataforma
spring.servlet.multipart.max-file-size=25MB

# Mostramos el SQL por consola para depuraciones y demostraciones.
spring.jpa.show-sql=true